# To build the entire stack run 'make run'

version: '3'

services:

  # This container is errbot
  chatbot:
    container_name: chatbot
    restart: always
    build: ./src/errbot
    env_file: 
      - ./config.env
      - ./creds.env
    depends_on:
      - localstack
    volumes:
      - log-volume:/app

  # This container is used to create a local 'mock' instance of AWS for testing
  localstack:
      container_name: localstack
      build:
        context: ./script/localstack
        dockerfile: ./Dockerfile
      ports:
        - "127.0.0.1:4566:4566"
        - "127.0.0.1:4571:4571"
      environment:
        - LOCALSTACK_HOST=http://localstack:4566
        - SERVICES=${SERVICES- }
        - DEBUG=${DEBUG- }
        - DATA_DIR=${DATA_DIR- }
        - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
        - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
        - DOCKER_HOST=unix:///var/run/docker.sock
      volumes:
        - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"

  # Containers for observability
  loki:
    container_name: loki
    image: grafana/loki:2.4.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.2
    volumes:
      - /var/log:/var/log
      - log-volume:/app:ro
      - ./script/promtail/config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
      - chatbot

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - promtail

volumes:
  log-volume: