# To build the entire stack run 'make run'
# To build just the errbot chatbot run 'make errbot'

version: '3.9'

services:
  chatbot:
    container_name: chatbot
    restart: always
    build: ./src/errbot
    env_file: 
      - ./config.env
      - ./creds.env
