apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: ${ACR_NAME}.azurecr.io/nginx:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.1"
              memory: "50Mi"
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_ADDR
              value: "uptime-kuma-service.uptime-kuma"
            - name: BACKEND_PORT
              value: "3001"
            - name: SERVER_NAME
              value: "errbot-status.birki.io"
            
