apiVersion: v1
kind: Service
metadata:
  name: nginx-errbot-service
  namespace: nginx
  labels:
    name: nginx
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    name: nginx
