# custom promtail config for local development
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: errbot
    static_configs:
      - targets:
          - localhost
        labels:
          job: errbot
          __path__: /app/errbot.log
    pipeline_stages:
    - match:
        selector: '{job="errbot"}'
        stages:
        - regex:
            expression: '(?P<timestamp>\d\d\d\d-\d\d-\d\d\s\d\d:\d\d:\d\d,\d\d\d)\s(?P<level>[a-zA-Z]+)\s+(?P<name>[a-zA-Z\.]+)\s+(?P<message>.*)'

        - labels:
            level:
            message:
