# custom promtail config for local development
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: errbot
    static_configs:
      - targets:
          - localhost
        labels:
          app: errbot
          __path__: /app/errbot.log
    pipeline_stages:
    - match:
        selector: '{app="errbot"}'
        stages:
        - regex:
            expression: '(?P<timestamp>\d\d\d\d-\d\d-\d\d\s\d\d:\d\d:\d\d,\d\d\d)\s(?P<level>[a-zA-Z]+)\s+(?P<name>[a-zA-Z\.]+)\s+(?P<message>.*)'

        - labels:
            level:
            message:

    # to scrape metrics use -> https://grafana.com/docs/loki/latest/clients/promtail/stages/metrics/
    # - match:
    #     selector: '{app="errbot"}'
    #     stages:
    #     # The regex stage tries to extract a Go panic by looking for panic:
    #     # in the log message.
    #     - regex:
    #         expression: '(?P<warning>\sWARNING\s\s\s\s\s)'

    #     # The metrics stage is going to increment a panic_total metric counter
    #     # which Promtail exposes. The counter is only incremented when panic
    #     # was extracted from the regex stage.
    #     - metrics:
    #         warning_total:
    #           type: Counter
    #           description: "total count of warnings"
    #           source: warning
    #           config:
    #             action: inc
