apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: localstack
  labels:
    name: localstack-claim1
  name: localstack-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
