apiVersion: v1
kind: ServiceAccount
metadata:
  name: localstack
  namespace: localstack
  labels:
    helm.sh/chart: localstack-0.3.7
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
