apiVersion: v1
kind: Secret
metadata:
  name: errbot-secret
  namespace: errbot
type: Opaque
data:
  CHAT_SERVICE_TOKEN: "${CHAT_SERVICE_TOKEN}"
  RIOT_TOKEN: "${RIOT_TOKEN}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}"
  SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
  SENTRY: "${SENTRY}"
  STATUS_PUSH_ENDPOINT: "${STATUS_PUSH_ENDPOINT}"
