apiVersion: v1
kind: Namespace
metadata:
  name: observability
spec: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: observability
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
